# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pysfm.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cmdinput = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmdinput.sizePolicy().hasHeightForWidth())
        self.cmdinput.setSizePolicy(sizePolicy)
        self.cmdinput.setEditable(True)
        self.cmdinput.setObjectName("cmdinput")
        self.cmdinput.addItem("")
        self.cmdinput.addItem("")
        self.cmdinput.addItem("")
        self.cmdinput.addItem("")
        self.horizontalLayout.addWidget(self.cmdinput)
        self.cmdbtn = QtWidgets.QPushButton(self.groupBox_2)
        self.cmdbtn.setObjectName("cmdbtn")
        self.horizontalLayout.addWidget(self.cmdbtn)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.serverlbl = QtWidgets.QLabel(self.groupBox)
        self.serverlbl.setObjectName("serverlbl")
        self.gridLayout_3.addWidget(self.serverlbl, 0, 0, 1, 1)
        self.serverinput = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverinput.sizePolicy().hasHeightForWidth())
        self.serverinput.setSizePolicy(sizePolicy)
        self.serverinput.setEditable(True)
        self.serverinput.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.serverinput.setObjectName("serverinput")
        self.gridLayout_3.addWidget(self.serverinput, 0, 1, 1, 1)
        self.userlbl = QtWidgets.QLabel(self.groupBox)
        self.userlbl.setObjectName("userlbl")
        self.gridLayout_3.addWidget(self.userlbl, 1, 0, 1, 1)
        self.userinput = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userinput.sizePolicy().hasHeightForWidth())
        self.userinput.setSizePolicy(sizePolicy)
        self.userinput.setEditable(True)
        self.userinput.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.userinput.setObjectName("userinput")
        self.gridLayout_3.addWidget(self.userinput, 1, 1, 1, 1)
        self.contactbtn = QtWidgets.QPushButton(self.groupBox)
        self.contactbtn.setObjectName("contactbtn")
        self.gridLayout_3.addWidget(self.contactbtn, 2, 1, 1, 1)
        self.messagelbl = QtWidgets.QLabel(self.groupBox)
        self.messagelbl.setObjectName("messagelbl")
        self.gridLayout_3.addWidget(self.messagelbl, 3, 0, 1, 1)
        self.messageinput = QtWidgets.QPlainTextEdit(self.groupBox)
        self.messageinput.setObjectName("messageinput")
        self.gridLayout_3.addWidget(self.messageinput, 4, 0, 1, 2)
        self.sendbtn = QtWidgets.QPushButton(self.groupBox)
        self.sendbtn.setObjectName("sendbtn")
        self.gridLayout_3.addWidget(self.sendbtn, 5, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.showonlineusersbtn = QtWidgets.QPushButton(self.groupBox_3)
        self.showonlineusersbtn.setObjectName("showonlineusersbtn")
        self.gridLayout_5.addWidget(self.showonlineusersbtn, 0, 1, 1, 1)
        self.showgroupbtn = QtWidgets.QPushButton(self.groupBox_3)
        self.showgroupbtn.setObjectName("showgroupbtn")
        self.gridLayout_5.addWidget(self.showgroupbtn, 0, 0, 1, 1)
        self.showallusersbtn = QtWidgets.QPushButton(self.groupBox_3)
        self.showallusersbtn.setObjectName("showallusersbtn")
        self.gridLayout_5.addWidget(self.showallusersbtn, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 360, 582))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.incmessageinput = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.incmessageinput.setPlainText("")
        self.incmessageinput.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.incmessageinput.setObjectName("incmessageinput")
        self.gridLayout.addWidget(self.incmessageinput, 1, 0, 1, 1)
        self.incmessagelbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.incmessagelbl.setObjectName("incmessagelbl")
        self.gridLayout.addWidget(self.incmessagelbl, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.scrollArea, self.incmessageinput)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PySFM"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Send server command"))
        self.cmdinput.setCurrentText(_translate("MainWindow", "showgroup"))
        self.cmdinput.setItemText(0, _translate("MainWindow", "showgroup"))
        self.cmdinput.setItemText(1, _translate("MainWindow", "creategroup"))
        self.cmdinput.setItemText(2, _translate("MainWindow", "deletegroup"))
        self.cmdinput.setItemText(3, _translate("MainWindow", "addgroup"))
        self.cmdbtn.setText(_translate("MainWindow", "Send"))
        self.groupBox.setTitle(_translate("MainWindow", "Send message"))
        self.serverlbl.setText(_translate("MainWindow", "Target server:"))
        self.userlbl.setText(_translate("MainWindow", "Target user:"))
        self.contactbtn.setText(_translate("MainWindow", "Add to contacts"))
        self.messagelbl.setText(_translate("MainWindow", "Message:"))
        self.sendbtn.setText(_translate("MainWindow", "Send"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Groups and users"))
        self.showonlineusersbtn.setText(_translate("MainWindow", "Show online users"))
        self.showgroupbtn.setText(_translate("MainWindow", "Show groups"))
        self.showallusersbtn.setText(_translate("MainWindow", "Show all users"))
        self.incmessagelbl.setText(_translate("MainWindow", "Incoming messsages:"))

